data_directory: 'path/to/data'
param_dist:
  n_estimators: [100, 200, 300]
  learning_rate: [0.01, 0.05, 0.1]
  subsample: [0.6, 0.8, 1.0]
  max_depth: [3, 4, 5]
  max_features: ['auto', 'sqrt', 'log2']
  min_samples_split: [2, 5, 10]
